#!/usr/bin/env node
/**
 * Pose Royale game scaffolder.
 *
 * Usage:
 *   pnpm create-game <kebab-id>                 # writes games/<id>/ with a working stub
 *   pnpm create-game <kebab-id> --name "Name"   # override the human-readable name
 *   pnpm create-game --list                     # show what would be written, no writes
 *
 * The generated package:
 *   • declares the GameModule contract (manifest + mount)
 *   • wires a canvas, hand tracker subscription, RAF loop, and destroy cleanup
 *   • emits a dummy raw score every frame so the orchestrator can show live scoring
 *   • compiles clean under the root typecheck and lint
 *
 * After creating a game, register it in apps/web/src/tournament/registry.ts and add the
 * workspace dep to apps/web/package.json. `create-game` prints both snippets at the end.
 */

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function parseArgs(argv) {
  const out = { id: null, name: null, dryRun: false };
  for (const arg of argv) {
    if (arg === "--list" || arg === "--dry-run") out.dryRun = true;
    else if (arg.startsWith("--name=")) out.name = arg.slice("--name=".length);
    else if (out.id === null) out.id = arg;
  }
  return out;
}

function titleCase(kebab) {
  return kebab
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(" ");
}

function validateId(id) {
  if (!/^[a-z][a-z0-9-]{2,40}$/.test(id)) {
    throw new Error(
      `Invalid game id "${id}". Use kebab-case, 3-40 chars, starting with a letter.`,
    );
  }
}

function fileMap(id, name) {
  const pkg = `@pose-royale/game-${id}`;
  return {
    [`games/${id}/package.json`]: JSON.stringify(
      {
        name: pkg,
        version: "0.1.0",
        private: true,
        type: "module",
        main: "./src/index.ts",
        types: "./src/index.ts",
        exports: { ".": "./src/index.ts" },
        scripts: {
          build: "tsc --noEmit",
          typecheck: "tsc --noEmit",
          test: "vitest run --passWithNoTests",
          lint: "eslint src",
        },
        dependencies: {
          "@pose-royale/sdk": "workspace:*",
        },
        devDependencies: {
          typescript: "~5.9.3",
          vitest: "^4.0.14",
        },
      },
      null,
      2,
    ) + "\n",

    [`games/${id}/tsconfig.json`]:
      JSON.stringify(
        { extends: "../../tsconfig.base.json", include: ["src/**/*"] },
        null,
        2,
      ) + "\n",

    [`games/${id}/src/manifest.ts`]: `import type { GameManifest } from "@pose-royale/sdk";

/** Auto-generated by scripts/create-game.mjs. Tune par, duration, and demo card before shipping. */
export const manifest: GameManifest = {
  id: "${id}",
  name: "${name}",
  shortDescription: "A brand new Pose Royale minigame.",
  version: "0.1.0",
  preferredDurationSec: 30,
  minPlayers: 1,
  maxPlayers: 2,
  cvRequires: ["hands"],
  scoring: "cumulative",
  par: 20,
  demo: {
    previewUrl: "/games/${id}/preview.webm",
    howToPlay: "Replace me — describe the core interaction in one sentence.",
    controls: [{ icon: "✋", label: "Index fingertip" }],
  },
};
`,

    [`games/${id}/src/index.ts`]: `/**
 * ${name} — auto-generated GameModule stub. Replace the RAF logic with your real game.
 *
 * The scaffold already handles:
 *   • canvas insertion + resize via ResizeObserver
 *   • hand-tracker subscription through ctx.hands
 *   • deterministic RNG via ctx.rng
 *   • score emission via ctx.emitScore
 *   • destroy() that cancels RAF, removes listeners, empties the DOM
 */

import type {
  GameContext,
  GameInstance,
  GameModule,
  HandFrame,
  Unsub,
} from "@pose-royale/sdk";
import { manifest } from "./manifest.js";

function mount(el: HTMLElement, ctx: GameContext): GameInstance {
  const canvas = document.createElement("canvas");
  canvas.style.width = "100%";
  canvas.style.height = "100%";
  canvas.style.display = "block";
  canvas.style.touchAction = "none";
  el.appendChild(canvas);

  const maybeCtx = canvas.getContext("2d");
  if (!maybeCtx) throw new Error("${id}: 2D canvas context unavailable");
  const g2d: CanvasRenderingContext2D = maybeCtx;

  let tipX: number | null = null;
  let tipY: number | null = null;
  const handSub: Unsub = ctx.hands.subscribe((frame: HandFrame) => {
    const h = frame.hands[0];
    if (!h) return;
    const lm = h.landmarks[8];
    if (lm) {
      tipX = 1 - lm.x;
      tipY = lm.y;
    }
  });

  function resize(): void {
    const rect = el.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.max(1, Math.floor(rect.width * dpr));
    canvas.height = Math.max(1, Math.floor(rect.height * dpr));
  }
  const ro = new ResizeObserver(resize);
  ro.observe(el);
  resize();

  let running = true;
  let paused = false;
  let rafId = 0;
  let rawScore = 0;

  const loop = (): void => {
    if (!running) return;
    rafId = requestAnimationFrame(loop);
    if (paused) return;

    g2d.clearRect(0, 0, canvas.width, canvas.height);
    g2d.fillStyle = "rgba(20,20,30,0.4)";
    g2d.fillRect(0, 0, canvas.width, canvas.height);

    g2d.fillStyle = "#fff";
    g2d.font = "bold 20px system-ui, sans-serif";
    g2d.fillText("${name} — replace me!", 24, 40);
    g2d.fillText("Score: " + rawScore, 24, 68);

    if (tipX !== null && tipY !== null) {
      g2d.fillStyle = "#7dd3fc";
      g2d.beginPath();
      g2d.arc(tipX * canvas.width, tipY * canvas.height, 12, 0, Math.PI * 2);
      g2d.fill();
      // Placeholder scoring: +1 every time the fingertip touches the top band.
      if (tipY < 0.15) rawScore += 1;
    }

    ctx.emitScore({ playerId: ctx.localPlayerId, raw: rawScore });
  };

  // Hint: ctx.rng() is deterministic per-round. Use it for spawn patterns so online peers
  // see the same level.
  void ctx.rng;

  return {
    start() {
      rafId = requestAnimationFrame(loop);
    },
    pause() {
      paused = true;
    },
    resume() {
      paused = false;
    },
    destroy() {
      running = false;
      cancelAnimationFrame(rafId);
      handSub();
      ro.disconnect();
      canvas.remove();
    },
  };
}

const gameModule: GameModule = { manifest, mount };
export default gameModule;
export { manifest, gameModule as module };
`,
  };
}

async function writeMap(files) {
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(ROOT, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, content, { flag: "wx" }).catch((err) => {
      if (err.code === "EEXIST") {
        throw new Error(`Refusing to overwrite existing file: ${rel}`);
      }
      throw err;
    });
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.id) {
    console.error(
      "Usage: pnpm create-game <kebab-id> [--name \"Display Name\"] [--list]\n\n" +
        "Example: pnpm create-game holeinthewall --name \"Hole In The Wall\"",
    );
    process.exit(1);
  }
  validateId(args.id);
  const name = args.name ?? titleCase(args.id);

  const files = fileMap(args.id, name);
  if (args.dryRun) {
    for (const rel of Object.keys(files)) console.log("would write:", rel);
    return;
  }
  await writeMap(files);

  const pkg = `@pose-royale/game-${args.id}`;
  console.log(`\n✓ Created games/${args.id}\n`);
  console.log("Next steps:");
  console.log(
    `  1. Add "${pkg}": "workspace:*" to apps/web/package.json dependencies`,
  );
  console.log(`  2. Register in apps/web/src/tournament/registry.ts:`);
  console.log(`       import { manifest as m } from "${pkg}";`);
  console.log(
    `       { id: m.id, manifest: m, load: () => import("${pkg}") },`,
  );
  console.log("  3. Run pnpm install to link the workspace");
  console.log("  4. Replace the stub loop in src/index.ts with your real gameplay");
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
